// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float4> StBuffer;
AppendStructuredBuffer<float4> AppendBuffer;
RWTexture2D<float4> RT;

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 color = float4(1, 1, 0, 0);
    AppendBuffer.Append(color);
    StBuffer[id.x * 128 + id.y] = color;
    RT[id.xy] = color;
}
